image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  image: amazonlinux
  script:
    - yum install -y aws-cli jq
    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - aws configure set region "us-east-1"
    - aws ecs update-service --cluster DevCluster --service webDeploy --force-new-deployment
    - aws ecs describe-tasks --cluster DevCluster --tasks arn:aws:ecs:us-east-1:735691669062:task/DevCluster/dcfa05f3747041d890011c7059813f40
  only:
    - main
