image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build:
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  image: amazonlinux
  script:
    - yum install -y aws-cli
    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - aws configure set region "$AWS_REGION"
    - TASK_DEF=$(sed -e "s|\"image\": \".*\"|\"image\": \"$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA\"|" task_definition.json)
    - aws ecs register-task-definition --cli-input-json "$TASK_DEF"
    - aws ecs update-service --cluster DevCluster --service web_deployment --force-new-deployment
 
  only:
    - main
