image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  script:
    - aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment
  only:
    - main
