stages:
  - test
  - deploy

test:
  image: python:3.8
  script:
    - pip install Flask
    - python app.py & curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:5000

deploy:
  stage: deploy
  script:
    - echo 'Here you would deploy your app to a server'

deploy_aws:
  script:
    - aws deploy create-deployment --application-name basic_flask_app --s3-location bucket=web-app-bucket-1,key=flask_app.zip,bundleType=zip --deployment-group-name deployment_group

