image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

test:
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker pull $IMAGE_NAME
    - docker run -d --name test_container -p 5000:5000 $IMAGE_NAME
    - apk --no-cache add curl # install curl
    - sleep 10 # give some time for the app to start
    - docker logs test_container
    - docker ps
    - curl -f http://0.0.0.0:5000/ || exit 1
    - sudo iptables -L -n -v
    - docker stop test_container
    - docker rm test_container



deploy:
  stage: deploy
  image: amazonlinux
  script:
    - yum install -y aws-cli jq
    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - aws configure set region "us-east-1"
    - aws ecs update-service --cluster DevCluster --service deployWeb --force-new-deployment
  only:
    - main
